# Generated by Django 5.2.8 on 2025-11-20 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_nivel_experiencia_userprofile_objetivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='ejercicios',
            field=models.ManyToManyField(blank=True, to='core.ejercicio'),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='nivel_experiencia',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='nombre',
            field=models.CharField(default='Plan personalizado', max_length=120),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='musculo',
            field=models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('core', 'Core'), ('fullbody', 'Full Body')], max_length=30),
        ),
        migrations.AlterField(
            model_name='planejercicio',
            name='repeticiones',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='planejercicio',
            name='series',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='planentrenamiento',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.objetivo'),
        ),
        migrations.AlterField(
            model_name='planentrenamiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
