# Generated by Django 5.2.8 on 2025-11-20 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rutina_rutinaejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaBaseEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(default=3)),
                ('repeticiones', models.CharField(default='10', max_length=20)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=15)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.rutinabase')),
            ],
        ),
    ]
