# Generated by Django 5.2.8 on 2025-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rutinabase_rutinabaseejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='repeticiones',
            field=models.CharField(default='10', max_length=20),
        ),
    ]
