# Generated by Django 5.2.8 on 2025-11-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rutinaejercicio_repeticiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejercicio',
            name='dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='lunes', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planejercicio',
            name='repeticiones',
            field=models.CharField(default='10', max_length=20),
        ),
    ]
