# Generated by Django 5.2.8 on 2025-11-20 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planejercicio_dia_alter_planejercicio_repeticiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_plan', to='core.planentrenamiento'),
        ),
    ]
