# Generated by Django 5.2.8 on 2025-11-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_plan_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutinaejercicio',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='rutinaejercicio',
            name='ejercicio',
        ),
        migrations.DeleteModel(
            name='Rutina',
        ),
        migrations.DeleteModel(
            name='RutinaEjercicio',
        ),
    ]
