# Generated by Django 5.2.8 on 2025-11-20 09:51

from django.db import migrations


OBJETIVOS_DEFAULT = [
    "Ganar masa muscular",
    "Subir de peso",
    "Bajar de peso",
    "Mantener peso",
    "Volumen",
    "Corte",
]


def create_objetivos(apps, schema_editor):
    Objetivo = apps.get_model('core', 'Objetivo')
    for nombre in OBJETIVOS_DEFAULT:
        Objetivo.objects.get_or_create(nombre=nombre)


def reverse_objetivos(apps, schema_editor):
    Objetivo = apps.get_model('core', 'Objetivo')
    Objetivo.objects.filter(nombre__in=OBJETIVOS_DEFAULT).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_rutinaejercicio_rutina_and_more'),
    ]

    operations = [
        migrations.RunPython(create_objetivos, reverse_code=reverse_objetivos),
    ]
