# Generated by Django 5.2.8 on 2025-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_objetivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinabase',
            name='nivel',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20),
        ),
    ]
