# Generated by Django 5.2.8 on 2025-11-20 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rutinabase_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=15)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('completado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.planentrenamiento')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('plan', 'dia', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='RoutineExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('peso_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('day_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='core.routinedaylog')),
                ('plan_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.planejercicio')),
            ],
        ),
    ]
