# Generated by Django 5.2.8 on 2025-11-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_routinedaylog_routineexerciselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejercicio',
            name='dia_label',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progreso',
            name='day_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='core.routinedaylog'),
        ),
        migrations.AddField(
            model_name='routinedaylog',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutinabaseejercicio',
            name='dia_label',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
