# Generated by Django 5.2.8 on 2025-11-20 10:14

from django.db import migrations

ROUTINES = [
    {
        "nombre": "Push Pull Legs",
        "nivel": "intermediate",
        "dias": [
            {
                "dia": "lunes",
                "label": "Push",
                "ejercicios": [
                    ("Press banca con barra", "pecho", 4, "6-8"),
                    ("Press inclinado con mancuernas", "pecho", 3, "8-10"),
                    ("Press militar con barra", "hombros", 4, "6-8"),
                    ("Elevaciones laterales con mancuernas", "hombros", 3, "12-15"),
                    ("Fondos en paralelas", "triceps", 3, "8-12"),
                    ("Extensión de tríceps en polea", "triceps", 3, "12-15"),
                ],
            },
            {
                "dia": "miercoles",
                "label": "Pull",
                "ejercicios": [
                    ("Dominadas pronas", "espalda", 4, "6-10"),
                    ("Remo con barra", "espalda", 4, "8-10"),
                    ("Remo en polea sentado", "espalda", 3, "12"),
                    ("Face pull", "hombros", 3, "15"),
                    ("Curl bíceps con barra", "biceps", 3, "8-10"),
                    ("Curl martillo", "biceps", 3, "10-12"),
                ],
            },
            {
                "dia": "viernes",
                "label": "Legs",
                "ejercicios": [
                    ("Sentadilla trasera", "piernas", 4, "5-8"),
                    ("Peso muerto rumano", "piernas", 4, "8-10"),
                    ("Prensa de piernas", "piernas", 3, "12"),
                    ("Zancadas caminando", "piernas", 3, "12"),
                    ("Elevación de talones de pie", "piernas", 4, "12-15"),
                    ("Plancha", "core", 3, "45s"),
                ],
            },
        ],
    },
    {
        "nombre": "Full Body Essentials",
        "nivel": "beginner",
        "dias": [
            {
                "dia": "lunes",
                "label": "Full Body A",
                "ejercicios": [
                    ("Sentadilla goblet", "piernas", 3, "12"),
                    ("Press banca con mancuernas", "pecho", 3, "10"),
                    ("Remo con mancuerna", "espalda", 3, "12"),
                    ("Press militar sentado", "hombros", 3, "10"),
                    ("Peso muerto rumano con mancuernas", "piernas", 3, "12"),
                    ("Crunch", "core", 3, "15"),
                ],
            },
            {
                "dia": "miercoles",
                "label": "Full Body B",
                "ejercicios": [
                    ("Peso muerto convencional", "piernas", 3, "8"),
                    ("Press inclinado con mancuernas", "pecho", 3, "10"),
                    ("Dominadas asistidas", "espalda", 3, "AMRAP"),
                    ("Press de hombro con mancuernas", "hombros", 3, "12"),
                    ("Curl bíceps alterno", "biceps", 3, "12"),
                    ("Extensión de tríceps en cuerda", "triceps", 3, "12"),
                    ("Plancha lateral", "core", 3, "30s"),
                ],
            },
            {
                "dia": "viernes",
                "label": "Full Body C",
                "ejercicios": [
                    ("Sentadilla frontal", "piernas", 3, "10"),
                    ("Press de pecho en máquina", "pecho", 3, "12"),
                    ("Remo con cable sentado", "espalda", 3, "12"),
                    ("Elevaciones laterales", "hombros", 3, "15"),
                    ("Hip thrust", "piernas", 3, "12"),
                    ("Ab wheel", "core", 3, "10"),
                ],
            },
        ],
    },
    {
        "nombre": "Tren Superior / Inferior",
        "nivel": "intermediate",
        "dias": [
            {
                "dia": "lunes",
                "label": "Superior Fuerza",
                "ejercicios": [
                    ("Press banca con barra", "pecho", 5, "5"),
                    ("Dominadas lastradas", "espalda", 5, "5"),
                    ("Press militar de pie", "hombros", 4, "6"),
                    ("Remo con barra Pendlay", "espalda", 4, "6"),
                    ("Curl bíceps con barra", "biceps", 3, "8"),
                    ("Press francés", "triceps", 3, "8"),
                ],
            },
            {
                "dia": "martes",
                "label": "Inferior Fuerza",
                "ejercicios": [
                    ("Sentadilla trasera", "piernas", 5, "5"),
                    ("Peso muerto convencional", "piernas", 5, "5"),
                    ("Prensa de piernas", "piernas", 4, "8"),
                    ("Curl femoral tumbado", "piernas", 3, "10"),
                    ("Elevación de talones sentado", "piernas", 4, "12"),
                ],
            },
            {
                "dia": "jueves",
                "label": "Superior Hipertrofia",
                "ejercicios": [
                    ("Press inclinado con mancuernas", "pecho", 4, "10"),
                    ("Remo en polea sentado", "espalda", 4, "12"),
                    ("Press Arnold", "hombros", 4, "12"),
                    ("Aperturas con mancuernas", "pecho", 3, "15"),
                    ("Face pull", "hombros", 3, "15"),
                    ("Curl predicador", "biceps", 3, "12"),
                    ("Extensión de tríceps en polea", "triceps", 3, "12"),
                ],
            },
            {
                "dia": "viernes",
                "label": "Inferior Hipertrofia",
                "ejercicios": [
                    ("Sentadilla frontal", "piernas", 4, "10"),
                    ("Peso muerto rumano", "piernas", 4, "10"),
                    ("Zancadas búlgaras", "piernas", 3, "12"),
                    ("Hip thrust", "piernas", 3, "12"),
                    ("Extensión de cuádriceps", "piernas", 3, "15"),
                    ("Plancha", "core", 3, "60s"),
                ],
            },
        ],
    },
    {
        "nombre": "Bro Split Clásico",
        "nivel": "advanced",
        "dias": [
            {
                "dia": "lunes",
                "label": "Pecho",
                "ejercicios": [
                    ("Press banca con barra", "pecho", 4, "8-10"),
                    ("Press inclinado con mancuernas", "pecho", 4, "10-12"),
                    ("Aperturas en máquina", "pecho", 3, "15"),
                    ("Fondos en paralelas", "triceps", 3, "AMRAP"),
                ],
            },
            {
                "dia": "martes",
                "label": "Espalda",
                "ejercicios": [
                    ("Dominadas pronas", "espalda", 4, "8-10"),
                    ("Remo con barra", "espalda", 4, "10"),
                    ("Remo con mancuerna", "espalda", 3, "12"),
                    ("Pulldown en polea", "espalda", 3, "15"),
                ],
            },
            {
                "dia": "miercoles",
                "label": "Hombros",
                "ejercicios": [
                    ("Press militar con barra", "hombros", 4, "8-10"),
                    ("Press Arnold", "hombros", 3, "12"),
                    ("Elevaciones laterales", "hombros", 4, "15"),
                    ("Pájaros con mancuernas", "hombros", 3, "15"),
                ],
            },
            {
                "dia": "jueves",
                "label": "Piernas",
                "ejercicios": [
                    ("Sentadilla trasera", "piernas", 4, "8-10"),
                    ("Prensa de piernas", "piernas", 4, "12"),
                    ("Peso muerto rumano", "piernas", 4, "10"),
                    ("Curl femoral sentado", "piernas", 3, "12"),
                    ("Elevaciones de talones", "piernas", 4, "15"),
                ],
            },
            {
                "dia": "viernes",
                "label": "Brazos/Core",
                "ejercicios": [
                    ("Curl bíceps con barra", "biceps", 4, "10"),
                    ("Curl martillo", "biceps", 3, "12"),
                    ("Press francés", "triceps", 4, "10"),
                    ("Extensión de tríceps en cuerda", "triceps", 3, "12"),
                    ("Crunch cable", "core", 3, "15"),
                    ("Plancha", "core", 3, "60s"),
                ],
            },
        ],
    },
]


def seed_rutinas(apps, schema_editor):
    RutinaBase = apps.get_model('core', 'RutinaBase')
    RutinaBaseEjercicio = apps.get_model('core', 'RutinaBaseEjercicio')
    Ejercicio = apps.get_model('core', 'Ejercicio')

    RutinaBase.objects.all().delete()

    for data in ROUTINES:
        rutina = RutinaBase.objects.create(nombre=data['nombre'], nivel=data['nivel'])
        for bloque in data['dias']:
            dia_label = f"{bloque['dia'].capitalize()} - {bloque['label']}"
            for nombre, musculo, series, repeticiones in bloque['ejercicios']:
                ejercicio, _ = Ejercicio.objects.get_or_create(
                    nombre=nombre,
                    defaults={'musculo': musculo}
                )
                RutinaBaseEjercicio.objects.create(
                    rutina=rutina,
                    ejercicio=ejercicio,
                    series=series,
                    repeticiones=repeticiones,
                    dia=bloque['dia'],
                    dia_label=dia_label,
                )


def remove_rutinas(apps, schema_editor):
    RutinaBase = apps.get_model('core', 'RutinaBase')
    nombres = [r['nombre'] for r in ROUTINES]
    RutinaBase.objects.filter(nombre__in=nombres).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_planejercicio_dia_label_progreso_day_log_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_rutinas, reverse_code=remove_rutinas),
    ]
